version: '3.8'

services:
  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: standalone